version: '3'
services:
    apiVps:
        build:
            context: .
        environment:
            - APP_NAME=vps-ssh-api
        ports:
            - "5000:5000"
        env_file:
            - .env
